version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - ./docker/proxy/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    logging:
      options:
        max-size: "4m"
        max-file: "10"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

volumes:
  vhost:
  html: